name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libsoup-3.0-dev

      - name: Clean previous dependencies (Unix)
        if: matrix.platform != 'windows-latest'
        run: |
          rm -rf node_modules
          rm -f deno.lock

      - name: Clean previous dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          if (Test-Path -Path "node_modules") { Remove-Item -Path "node_modules" -Recurse -Force }
          if (Test-Path -Path "deno.lock") { Remove-Item -Path "deno.lock" -Force }

      - name: Install frontend dependencies
        run: |
          deno install
          deno cache --reload vite.config.ts
          deno cache --reload src/main.tsx

      - name: Build the app
        run: |
          deno task build
          deno task tauri build

      - name: List build files (Debug)
        run: |
          find src-tauri/target/release/bundle -type f -name "*.*" | sort

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-bundle
          path: |
            src-tauri/target/release/bundle/**/*
          if-no-files-found: warn

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.app.tar.gz
            src-tauri/target/release/bundle/**/*.app.zip
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.nsis.zip
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
